spring:
  kafka:
    bootstrap-servers:
    - localhost:9091
    template:
      default-topic: first-topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
